[project]
name = "core"
version = "0.1.0"
description = "News aggregation core library"
dependencies = [
    "beautifulsoup4",
    "httpx",
]

[build-system]
requires = ["uv_build>=0.9.15,<0.10.0"]
build-backend = "uv_build"
